### ISSUE TITLE
Freeze with 720p dashboards on v1.0/1.1 Motherboards

### ISSUE THREAD

**Issue by nightowl3090** [MakeMHz/xbox-hd-plus#16] opened 2021-03-20 15:28 UTC
Dashboards running at a 720p resolution will lock up and freeze the Xbox (audio stops playing too) 5-10 seconds after initially loading the dashboard. Navigating to less visually complex menus or immediately loading a game can circumvent the issue. But navigating back to the main menu on Xbmc4gamers or letting the Screensaver load on EvolutionX will cause a freeze and lock. Multiple individuals have noted this issue. Removing the makemhz board from a v1.0/1.1 and installing it in a v1.4 motherboard resolves the issue, making it seem that it is specific to those motherboard revisions. Issue persisted with M8+ and IND5003 BIOS. Individuals also reported that the latest M8+ kernal patch does not resolve the issue.

**Comment by Teamshake** [comment] 2021-06-26 14:30
same thing was happening to me to me on a 1.0 board.  i thought there was something wrong with the xbox board so i ended up moving the hdmi mod to a different xbox.  i should have checked here first.

**Comment by robbiejmsn** [comment] 2021-06-26 23:28
Same on mine too. Thought it was my hdd about to kick the bucket.

**Comment by LoveMHz** [comment] 2021-06-26 23:41
Often the case is unnecessarily long wires or bad capacitors causing noise to lock up the GPU. This is covered in part in our last update here. https://makemhz.com/blogs/news/makemhz-and-xboxhd-update

In other cases, it seems to 'pre-coma' related or due to the CPU upgrade mod. If you believe the issue is not related to long wires or bad capacitors then please reach out to support@makemhz.com so we can work out the issue as the new QSB design should help with any signal noise issues (even those with poor/failing capacitors).

**Comment by Teamshake** [comment] 2021-06-27 03:34
just a note as ive removed mine from the 1.0 console (stock cpu) so not able to troubleshoot issue.  i had used the wire length from the install guide and i used the same wires when i transplanted it to a 1.4 board which is working.  only thing new was the flex cable as i ordered are replacement.  also the console had been recently recapped.  i did not replace the smd caps, only the through hole, so i guess it could be one of those smd caps causing an issue.

**Comment by Justawajz** [comment] 2022-05-22 23:04
Any update to this?  Just installed a HD+ in a 1.0 with new caps and also having this issue.

**Comment by robbiejmsn** [comment] 2022-05-23 05:28
Yes, it's being tested in beta and will be implemented in an update shortly.

**Comment by LoveMHz** [comment] 2022-06-10 22:34
Resolved in FW2.1.x

**Closed by LoveMHz** 2022-06-10 22:34 UTC
