### ISSUE TITLE
Stereo Only Audio

### ISSUE THREAD

**Issue by Nomar383** [MakeMHz/xbox-hd-plus#26] opened 2021-09-21 02:41 UTC
I have a v1.0 mobo with an XboxHD+ freshly installed. I'm using the M8+ BIOS with the latest kernel patch and HD+ App installed. Whether I have the HD+ App set audio to "Compatibility" or "Auto", I cannot get 5.1 audio to work. I am only getting stereo audio in game and in dashboard.

If I use the same BIOS without the HD+ kernel patch, I can set the audio in the dashboard and it saves my settings and plays 5.1 audio in game.

**Comment by Kobeskillz** [comment] 2022-01-31 20:40
I'm having the same issue! It's so frustrating.

**Comment by Nomar383** [comment] 2022-01-31 22:24
Yeah, I’ve been waiting since September without an update of any kind, as you can see. Seems like a low priority unfortunately

**Comment by LoveMHz** [comment] 2022-01-31 22:45
Just a heads up/warning. Commentary, anything that doesn't contribute to the issue, will be removed.

The issue is being looked into.

**Comment by KylJoy** [comment] 2022-02-03 20:48
Me also.

**Comment by KylJoy** [comment] 2022-02-03 20:48
I am also experiencing this issue with same setup.

**Comment by Commander1024** [comment] 2022-02-03 20:53
This is btw. an issue tracker. Not a democratic vot to force someone fix things. This issue is know and being worked on currently. That's why it exists. Contributing additional information is wanted. Adding pressure on Dustin by complaining doesn't solve anything.
Its also not an eventually coming up issue. Every HD+ with 2.x firmware is affected by this bug.

**Comment by Kobeskillz** [comment] 2022-02-03 21:36
> This is btw. an issue tracker. Not a democratic vot to force someone fix things. This issue is know and being worked on currently. That's why it exists. Contributing additional information is wanted. Adding pressure on Dustin by complaining doesn't solve anything. Its also not an eventually coming up issue. Every HD+ with 2.x firmware is affected by this bug.


My bad. Sorry for complaining that Dolby Digital one of the main features of the xbox does not work on this mod we paid money for. Pressure should be applied. Sorry that's how it works. You sell a product that does not list a main feature broken then you should get pressure to fix it. 

Complaining about people complaining about a broken feature in a product we paid hard earn money for is bad. Is ok lets sweep this under the rug and i'll wait for them to maybe or maybe not fix it.

**Comment by LoveMHz** [comment] 2022-06-10 22:33
Resolved in FW2.1.x

**Closed by LoveMHz** 2022-06-10 22:33 UTC
